### ISSUE TITLE
c++: fatal error: Killed signal terminated program cc1plus compilation terminated.

### ISSUE THREAD

**Issue by edjust** [nmilosev/pytorch-arm-builds#10]
I am stuck in the build process. I am using Raspberry Pi 3. Could anyone help me?

bash-5.0# python setup.py bdist_wheel
The use of NO_CUDA is deprecated and will be removed on Feb 20, 2020.Please use USE_CUDA instead.
The use of NO_MKLDNN is deprecated and will be removed on Feb 20, 2020.Please use USE_MKLDNN instead.
The use of NO_DISTRIBUTED is deprecated and will be removed on Feb 20, 2020.Please use USE_DISTRIBUTED instead.
Building wheel torch-1.4.0a0+139fec2
-- Building version 1.4.0a0+139fec2
cmake --build . --target install --config Release -- -j 4
[  1%] Built target clog
[  1%] Built target pthreadpool
[  2%] Built target libprotobuf-lite
[  4%] Built target c10
[  8%] Built target libprotobuf
[  8%] Built target foxi_loader
[  8%] Built target ATEN_CPU_FILES_GEN_TARGET
[  8%] Built target common
[  8%] Built target mkrename
[ 37%] Built target python_copy_files
[ 37%] Built target mkalias
[ 37%] Built target mkmasked_gnuabi
[ 37%] Built target mkrename_gnuabi
[ 37%] Built target mkdisp
[ 37%] Built target arraymap
[ 37%] Built target generate-torch-sources
[ 37%] Built target torch_python_stubs
[ 37%] Built target cpuinfo
[ 37%] Built target nnpack_reference_layers
[ 38%] Built target cpuinfo_internals
[ 38%] Built target __aten_op_header_gen
[ 38%] Built target renamePUREC_SCALAR.h_generated
[ 38%] Built target renameADVSIMD.h_generated
[ 42%] Built target libprotoc
[ 42%] Built target alias_advsimd.h_generated
[ 42%] Built target renameADVSIMDNOFMA.h_generated
[ 42%] Built target sleefdetpurec_scalar
[ 42%] Built target renamePURECFMA_SCALAR.h_generated
[ 42%] Built target headers
[ 42%] Built target protoc
[ 45%] Built target qnnpack
[ 45%] Built target sleefpurec_scalar
[ 47%] Built target nnpack
[ 49%] Built target pytorch_qnnpack
[ 49%] Built target sleefadvsimd
[ 50%] Built target sleefdetadvsimd
[ 50%] Built target sleefadvsimdnofma
[ 50%] Built target sleefdetadvsimdnofma
[ 50%] Built target sleefpurecfma_scalar
[ 50%] Built target sleefdetpurecfma_scalar
[ 50%] Built target Caffe2_PROTO
[ 50%] Built target gen_onnx_proto
[ 50%] Built target sleef
[ 50%] Built target caffe2_protos
[ 51%] Built target onnx_proto
[ 53%] Built target onnx
[ 53%] Building CXX object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/MemoryOverlap.cpp.o
[ 53%] Building CXX object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/ParallelCommon.cpp.o
[ 53%] Building CXX object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/ParallelNative.cpp.o
[ 53%] Building CXX object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/ParallelNativeTBB.cpp.o
[ 53%] Building CXX object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/ParallelThreadPoolNative.cpp.o
[ 53%] Building CXX object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/ParallelOpenMP.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
gmake[2]: *** [caffe2/CMakeFiles/torch.dir/build.make:399: caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/ParallelThreadPoolNative.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
gmake[2]: *** [caffe2/CMakeFiles/torch.dir/build.make:321: caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/MemoryOverlap.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1590: caffe2/CMakeFiles/torch.dir/all] Error 2
gmake: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 751, in <module>
    build_deps()
  File "setup.py", line 310, in build_deps
    cmake=cmake)
  File "/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/pytorch/tools/setup_helpers/cmake.py", line 334, in build
    self.run(build_args, my_env)
  File "/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib64/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.

**Comment by sungjuGit** [comment]
I have created wheel files for pytorch 1.4.0 and pytorch vision 0.5.0 directly on a Raspberry Pi 4B running Raspbian Buster.

https://github.com/sungjuGit/Pytorch-and-Vision-for-Raspberry-Pi-4B 

I could install them on a different Raspberry Pi 4B without any problem.  And I think you should be able to install the same wheel files on Pi 3 if you upgrade it to Raspbian Buster.

Be sure to install all dependencies for pytorch and pytorch vision.

https://sites.google.com/view/steam-for-vision/raspberry-pi/PytorchRP4
