### ISSUE TITLE
 is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by aminio101** [nmilosev/pytorch-arm-builds#2]
hi
i wanna install torch on raspberry pi3 b+ with ubuntu 64bit
when compile pytorch get this error

`Building wheel torch-1.2.0a0+8fdbe1e
-- Building version 1.2.0a0+8fdbe1e
cmake --build . --target install --config Release -- -j 4
make: *** No rule to make target 'install'.  Stop.
Traceback (most recent call last):
  File "setup.py", line 748, in <module>
    build_deps()
  File "setup.py", line 321, in build_deps
    cmake=cmake)
  File "/home/ubuntu/pytorch/tools/build_pytorch_libs.py", line 64, in build_caffe2
    cmake.build(my_env)
  File "/home/ubuntu/pytorch/tools/setup_helpers/cmake.py", line 323, in build
    self.run(build_args, my_env)
  File "/home/ubuntu/pytorch/tools/setup_helpers/cmake.py", line 82, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.` 

when run this command `git submodule update --init --recursive` haven't any output !!!??

and when we want to install with your *.whl file get this error 
`torch-1.1.0-cp37-cp37m-linux_aarch64.whl is not a supported wheel on this platform.`

**Comment by aminio101** [comment]
please help me to solve this issue
install fedora on raspi 3b+ 
install torch from whl file 
but when import torch get this blow error
`[root@localhost pytorch-arm-builds]# python3
Python 3.7.3 (default, May 11 2019, 00:22:29)
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.7/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory`

**Comment by nmilosev** [comment]
Please send me the output of `uname -a` and also you can try to install the armhfp version, should also work on your device! 

Let me know anyways.

**Comment by nmilosev** [comment]
Okay, so it seems your kernel is calling the architecture `arm64` and not `aarch64`. So let's try the following, rename `torch-1.1.0-cp37-cp37m-linux_aarch64.whl` to `torch-1.1.0-cp37-cp37m-linux_arm64.whl` and try again. That should get you through the first check.

**Comment by aminio101** [comment]
thank you
my problem form python version 
update and solved

but run so slow

**Comment by marcusvlc** [comment]
@aminio101 What version of python did you use to install? And which system?

**Comment by doryan-gonin** [comment]
> @aminio101 What version of python did you use to install? And which system?

I have a similar issue to what @aminio101 was describing `torch-1.1.0-cp37-cp37m-linux_aarch64.whl` is not a supported wheel on this platform`
I'm 90% sure my problem is also caused by an incorrect Python version (I have Python 3.9.2 on my Pi 2 model B V1.1 instead of the 3.7 that is used for the wheel)
I tried downloading python 3.7 and setting it as main when python3 is called but I didn't suceed.
Do you perhaps have a working python 3.9 wheel or a way of making it work ?
